In [1]:
l = [32132,8789,989898]

In [2]:
l

[32132, 8789, 989898]

In [3]:
l[1:]

[8789, 989898]

In [4]:
l[0:2]

[32132, 8789]

In [5]:
l[::2]

[32132, 989898]

---

In [8]:
import numpy as np

In [11]:
a=np.array([8475,454598,8989,454,4545,4545])

In [12]:
a

array([  8475, 454598,   8989,    454,   4545,   4545])

In [13]:
a[2:]

array([8989,  454, 4545, 4545])

In [14]:
a[2:4]

array([8989,  454])

In [15]:
b = a[2:4]

In [16]:
b

array([8989,  454])

In [17]:
b[0]

8989

In [18]:
b{:}

SyntaxError: invalid syntax (3535620302.py, line 1)

In [19]:
b[""]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [20]:
b[:]

array([8989,  454])

In [21]:
b[:]=111

In [22]:
a

array([  8475, 454598,    111,    111,   4545,   4545])

In [23]:
c = a.copy()

In [24]:
c

array([  8475, 454598,    111,    111,   4545,   4545])

In [25]:
c[0]=0

In [26]:
c

array([     0, 454598,    111,    111,   4545,   4545])

In [27]:
a

array([  8475, 454598,    111,    111,   4545,   4545])